version: '2'
services:
 server1:
  build: ./server1
  ports:
   - 8000:8000
  environment:
    - PORT=8000
  volumes:
   - ./server1:/usr/app
 server2:
  build: ./server2
  ports:
   - 8001:8001
  environment:
   - PORT=8001
  volumes:
   - ./server2:/usr/app


